FROM jupyter/datascience-notebook:678ada768ab1

COPY ./requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

COPY jupyter_notebook_config.py /etc/jupyter/

# Fix permissions on /etc/jupyter as root
USER root
RUN fix-permissions /etc/jupyter/

# Switch back to jovyan to avoid accidental container runs as root
USER 1000